### ISSUE TITLE
Problem on macOS Sierra

### ISSUE THREAD

**Issue by xpechoultres** [textmate/subversion.tmbundle#16]
Every command return this error :

```
svn: E170013: Unable to connect to a repository at URL 'http://******'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

```

SVN run fine under Terminal.app

**Comment by sorbits** [comment]
The bundle commands run `svn` with `--non-interactive` which means that `svn` must be able to find the (correct) password somewhere.

From the error, it sounds like you either have no password stored, or maybe a wrong/old password.

Try run with `--non-interactive` from a terminal, if it gives same error, look at your subversion config file, keyring, Keychain Access, etc. and remove all passwords stored, then do one interactive `svn` command from terminal where it should hopefully ask for password and store the correct one in the proper place.

I haven’t used `svn` for years, so I am not familiar with where and how it stores passwords, but
Googling the error code gives a lot of results, so I suggest you turn to Google or possibly the mailing list.

Closing as I don’t believe this to be an issue with the bundle per se.
